### ISSUE TITLE
目录不一样，不太知道怎么配置org mode GTD

### ISSUE THREAD

**Issue by glepnir** [Yangruipis/emacs_setting#2]
## Problem
 刚装了的spacemacs develop ，看了你的目录不太一样，你的`.spacemacs`在`.emacs.d` 中？我移进去，它还是会给我生成一个，`init.el` 设置GTD那里不是很懂，希望能交流学习一下。我是个vimer准备用emcas做时间管理，不准备做开发，所以简单能用GTD就可以。 
tanks a lot

**Comment by glepnir** [comment]
配置好了。能使用，但是还是有点不知无从下手。。能否请教一二

**Comment by Yangruipis** [comment]
额不好意思，.spacemacs应该在.emacs.d目录外面，你现在是到哪一步了？agenda和capture可以做到嘛

**Comment by Yangruipis** [comment]
@taigacute

**Comment by glepnir** [comment]
@Yangruipis  能用了，但是一些org的操作还是不太懂。比如开始时间结束时间 进度。还是不太懂，在看些org的书写教程。有点晕。
